name: affiliate_store
description: تطبيق محادثات جذاب مع استيراد واتساب
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  whats_json: ^1.0.0      # لتحليل ملفات واتساب
  provider: ^6.1.0        # لإدارة الحالة
  intl: ^0.19.0           # لتنسيق التواريخ
  google_fonts: ^6.2.1    # للخطوط الجميلة

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
