name: affiliate_store
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # حزم فايربيز لقاعدة البيانات
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  # حزم رفع الصور و Cloudinary
  image_picker: ^1.1.2
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
